### ISSUE TITLE
Getting error when running the forms flow forms 

### ISSUE THREAD

**Issue by abhishekbeesony** [AOT-Technologies/forms-flow-ai#81] opened 2021-05-06 11:15 UTC
Hello, 

Can you please help why are getting this kind of error ?

![image](https://user-images.githubusercontent.com/66721640/117289679-f0db9700-ae7d-11eb-8261-dfc14d0f3da6.png)

**Comment by abhilash-aot** [comment] 2021-05-26 07:04
Have created a JIra ticket at our side to look into this issue. Will update once its fixed. Thanks.

**Comment by abhilash-aot** [comment] 2021-06-11 14:58
The issue is fixed in new release. 
- For further update on this try` docker volume prune` to remove any dangling images.  and delete the mongod folder in the deployment folder and start the forms-flow-forms again with up --build option

**Closed by abhilash-aot** 2021-06-11 14:58 UTC
Labels: bug
