### ISSUE TITLE
how to deploy the data across multiple environments: from dev -> staging -> production

### ISSUE THREAD

**Issue by man-chi** [AOT-Technologies/forms-flow-ai#151] opened 2021-09-29 08:15 UTC
after we setup all the form in form.io,  process model in the dev env, is it possible to automate the deployment such as exporting the data and import to Staging and also production? otherwise, it will be manually configuring all the form and process in each environments which will be subjected to manual mistakes and errors. 

kindly advise.

**Comment by shibin-aot** [comment] 2021-09-29 08:48
The feature is still in the alpha stage of release to our open source. You can expect the import/export feature in the upcoming releases. We will confirm the release details on the same thread.
Meanwhile, you can use form.io own rest endpoints to do the export from formsflow.ai as well, it works. Let me know if I answered you.

**Comment by shibin-aot** [comment] 2021-10-04 05:13
I will close this issue since this is not a bug, but an upcoming feature, and I hope I answered you.

**Closed by shibin-aot** 2021-10-04 05:13 UTC

**Comment by man-chi** [comment] 2021-10-05 10:12
may I have when is the release date for the import/export form data from the form.io ?
